name: ðŸš€ Apis on push

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2

    - name: ðŸ“‚ Print current directory
      run: pwd  # This prints the current working directory

    - name: ðŸ“‚ Deploy files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: "ftp.psalmedu.com"  # Your FTP server
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: "./"  # Adjust to point to your project's public directory
        server-dir: "/"  # Change to your appropriate server path
        include: |  # Use include to specify files and directories to deploy
          node_modules/
          vendor/
          storage/
          tests/
          *.md
          .env
          lost+found/

    - name: ðŸš€ Post-Deployment
      run: echo "Deployment complete!"
